### ISSUE TITLE
I can't host on an insecure (HTTP) server. (crypto.randomUUID is not found)

### ISSUE THREAD

**Issue by mcfnord** [dtinth/jamulus-lounge#1]
Hi dtinth.

I got this far:

http://134.122.26.75/

I doubt my reverse proxy is right. I think I should put this repo into /www/var/html/. I made a mess by copying just some files. But the JavaScript console chokes on /listeners ... maybe the proxy needs to pass this explicitly. Because nginx handles this with a 404. Hmm.

John

**Comment by dtinth** [comment]
Does accessing `localhost:9998` work? (You can set up ssh tunnel so that `localhost:9998` gets forwarded to the remote host, e.g. `ssh -L 9998:localhost:9998 server.hostname`)

- If yes, then the problem is with the reverse proxy.
- If no, then jamulus-lounge is not properly configured — in this case try viewing the logs of docker compose project.

**Comment by mcfnord** [comment]
Yes, the proxy works now. It proxies everything now.

But now it's saying **Uncaught (in promise) TypeError: crypto.randomUUID is not a function**

This is probably because the node.js version is old. But docker-compose.yml says the server module uses **image: node:16**, and Node.js v16 should have that function. Hmm.

**Comment by dtinth** [comment]
In the browser, the `crypto` API requires a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#when_is_a_context_considered_secure) to become available. Please make sure to open the webpage in a secure context. There are considered secure context:

- `localhost`
- HTTPS

**Comment by dtinth** [comment]
I saw your changed issue title. Right now non-secure context is not supported, please set up HTTPS.

- If you have a domain name that you can use, I recommend using https://caddyserver.com/ — it automatically sets up Let's Encrypt. [Here's my notes on setting up a reverse proxy server.](https://notes.dt.in.th/CaddyReverseProxy)
- Otherwise, you can try using Cloudflare Quick Tunnels — https://blog.cloudflare.com/quick-tunnels-anytime-anywhere/

**Comment by mcfnord** [comment]
All set up at https://lounge.jamulus.live !

**Comment by dtinth** [comment]
Please make sure your reverse proxy is able to handle **streaming response** and does not buffer the response from the upstream.

(If you are using nginx, buffering is on by default and you have to disable it. https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/#configuring-buffers)

**Comment by mcfnord** [comment]
Ok, I added **proxy_buffering off;** to **sites-available/default**.
